services:
  kafka-0:
    image: docker.io/bitnami/kafka:3.9
    ports:
      - "9097:9097"
      - "9095:9095"
    networks:
      - kafka-net
    environment:
      # KRaft settings
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka-0:9093,1@kafka-1:9093
      - KAFKA_KRAFT_CLUSTER_ID=aaaaaaa
      # Listeners
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9097,CONTROLLER://:9093, EXTERNAL://:9095
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-0:9097, EXTERNAL://localhost:9095
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true # автоматическое создание топика

      - KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR=2
  kafka-1:
    image: docker.io/bitnami/kafka:3.9
    ports:
      - "9098:9098"
      - "9096:9096"
    networks:
      - kafka-net
    environment:
      # KRaft settings
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka-0:9093,1@kafka-1:9093
      - KAFKA_KRAFT_CLUSTER_ID=aaaaaaa
      # Listeners
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9098, CONTROLLER://:9093, EXTERNAL://:9096
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-1:9098, EXTERNAL://localhost:9096
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT, EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true # автоматическое создание топика

      - KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR=2

networks:
  kafka-net:
    driver: bridge

# кластер Kafka с двумя брокерами (kafka-0 и kafka-1) в режиме KRaft (Kafka Raft Metadata mode)
# ДЛя producer и consumer 9095 и 9096 